### ISSUE TITLE
Redesign templates to have .github/workflows not generated by cookiecutter

### ISSUE THREAD

**Issue by simonw** [simonw/python-lib-template-repository#2]
The templates currently require you to rename the `.github/rename-this-to-workflows` directory, which is crufty.

Instead, they could ship copies of those files in https://github.com/simonw/python-lib-template-repository/tree/main/.github/workflows

And the `cookiecutter.yml` file could delete itself after running (which is allowed - you can delete workflows, you just can't modify or add them).

**Comment by simonw** [comment]
The `test.yml` and `publish.yml` workflows need to NOT run on the main template repo.

They should only run on the generated repos after the `setup.py` file has been created.

**Comment by simonw** [comment]
Looks like GitHub changed it so newly created repos from templates don't have actions enabled!

**Comment by simonw** [comment]
Only that happens sometimes and doesn't happen other times? Weird.

**Comment by simonw** [comment]
Building this in https://github.com/simonw/python-lib-template-repository-2

**Comment by simonw** [comment]
Trying not to run tests unless setup.py file has been created is hard.

Tried this:

```yaml
jobs:
  test:
    if: ${{ always() && hashFiles('setup.py') }}
    runs-on: ubuntu-latest
```
And got this error:
`The workflow is not valid. .github/workflows/test.yml (Line: 7, Col: 9): Unrecognized function: 'hashFiles'. Located at position 13 within expression: always() && hashFiles('setup.py')`

Even though this says that should work: https://github.community/t/is-the-hashfiles-function-actually-available-in-the-if-context/202545/3?u=simonw

**Comment by simonw** [comment]
I think this works:
```yaml
name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      if: hashFiles('setup.py')
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: '**/setup.py'
    - name: Install dependencies
      if: hashFiles('setup.py')
      run: |
        pip install -e '.[test]'
    - name: Run tests
      if: hashFiles('setup.py')
      run: |
        pytest
```

**Comment by simonw** [comment]
OK, got it working.

`test.yml`:

```yaml
name: Test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      if: hashFiles('setup.py')
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: '**/setup.py'
    - name: Install dependencies
      if: hashFiles('setup.py')
      run: |
        pip install -e '.[test]'
    - name: Run tests
      if: hashFiles('setup.py')
      run: |
        pytest
```

It has workflow dispatch so you can manually trigger it after first creating the repo (it won't trigger on first creation because `setup.py` does not exist, but is then created by another action which doesn't trigger test runs).

It uses the `if: hashFiles('setup.py')` to avoid causing an error if `setup.py` does not exist yet.

**Comment by simonw** [comment]
And `cookiecutter.yml` which I think I'll rename to `setup.yml`:

```yaml
name: Execute template to populate repository

on:
  push:
  workflow_dispatch:

jobs:
  run-cookiecutter:
    if: ${{ github.repository != 'simonw/python-lib-template-repository-2' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Install cookiecutter
        run: pip3 install cookiecutter

      - uses: actions/github-script@v4
        id: fetch-repo-and-user-details
        with:
          script: |
            const query = `query($owner:String!, $name:String!) {
              repository(owner:$owner, name:$name) {
                name
                description
                owner {
                  login
                  ... on User {
                    name
                  }
                  ... on Organization {
                    name
                  }
                }
              }
            }`;
            const variables = {
              owner: context.repo.owner,
              name: context.repo.repo
            }
            const result = await github.graphql(query, variables)
            console.log(result)
            return result

      - name: Rebuild contents using cookiecutter
        env:
          INFO: ${{ steps.fetch-repo-and-user-details.outputs.result }}
        run: |
          export REPO_NAME=$(echo $INFO | jq -r '.repository.name')
          # Run cookiecutter
          pushd /tmp
          cookiecutter gh:simonw/python-lib --no-input \
            lib_name=$REPO_NAME \
            description="$(echo $INFO | jq -r .repository.description)" \
            github_username="$(echo $INFO | jq -r .repository.owner.login)" \
            author_name="$(echo $INFO | jq -r .repository.owner.name)"
          popd
          # Move generated content to root directory of repo
          mv /tmp/$REPO_NAME/* .
          # And .gitignore too:
          mv /tmp/$REPO_NAME/.gitignore .
          # Delete the cookiecutter.yml workflow, it has served its purpose
          rm .github/workflows/cookiecutter.yml

      - name: Force push new repo contents
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Initial library structure"
          push_options: --force
```
